[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 9999
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/"
]

[fmt]
int_types="short"
single_line_statement_blocks = "single"
multiline_func_header = "attributes_first"
sort_imports = true
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
